created classes
shahnawaza75/Oop_School_Library pull request #1
Opened 2022-08-23 18:50 UTC by shahnawaza75

Project requirements

Create class Person with the following:
Instance vars: @id, @name, and @age.
Constructor with name, age, and parent_permission as parameter. name and parent_permission are optional and have default values of "Unknown" and true.
Getters for @id, @name, and @age.
Setters for @name and @age.
Private method is_of_age? that returns true if @age is greater or equal to 18 and false otherwise.
Public method can_use_services? that returns true if person is of age or if they have permission from parents.
Create class Student with the following:
Inherits from Person.
Constructor extends parent's constructor by adding @classroom and a parameter for it.
Method play_hooky that returns "¯\(ツ)/¯".
Create class Teacher with the following:
Inherits from Person.
Constructor extends parent's constructor by adding @specialization and a parameter for it.
Override can_use_services? so it always returns true.
Each class should be saved in a separate file.

2022-08-23 20:18 UTC, brytebee requested changes
Hi, @shahnawaza75👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

You have submitted a project, that has failed linters. Kindly fix them and ask for another review on your dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-23 20:18 UTC, brytebee commented on person.rb
> +      @age = age
- [ ] **Required:** Kindly create an instance variable `@parent_permission` from your input `_parent_permission`. As currently is, it comes into the program as an input but it's useless to the program because it was never used.

2022-08-23 20:18 UTC, brytebee commented on person.rb
> +      return true if is_of_age?
- [ ] **Required:** Kindly update the can_use_services? method such that a person can use services if:
   - is_of_age
   - @parent_permission is true.
- [ ] `is_of_age?` would throw an error here since you have defined the method as `of_age?` above. Kindly stay consistent with the method names.
- [ ] It is possible to structure your class as you have done. The methods below the initialize method are automatically `public`, a `private` method and then using the modifier `public` to define a `public` class again. However, it is conventional to write all `public` methods before using the `private` access modifier to define the `private` methods.

2022-08-24 13:03 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @shahnawaza75 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/is14HLE2EUHPryPkmU/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used correct GitFlow
✔️ Created Person, Student and Teacher classes
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 13:03 UTC, codepantha commented on person.rb
> +  end
- [ ] Kindly create instance variable, `@parent_permission to equal your `_parent_permission` parameter as you will need it further down in the `can_use_services?` method

2022-08-24 13:03 UTC, codepantha commented on person.rb
> +  end
- [ ] Kindly modify the `can_use_services?` method so that it returns true if person is of age or if they have permission from parents
- [ ] `is_of_age?` is not defined and would throw an error. I believe the method you wanted to call is `of_age?`. Kindly rename `of_age?` to `is_of_age?` to ensure consistency

2022-08-24 13:42 UTC, mikethreels approved these changes
Hi Ali, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 14:30 UTC, merged